# Generated by Django 4.2.7 on 2023-12-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_useraddress_delete_userandress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="cep",
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="usuariocomplemento",
            name="cpf",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="usuariocomplemento",
            name="telefone",
            field=models.CharField(max_length=16),
        ),
    ]
