# Generated by Django 4.2.7 on 2023-12-07 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("possui_alergia", models.BooleanField(default=False)),
                (
                    "qual_alergia",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicos.animal",
                    ),
                ),
                (
                    "porte_animal_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicos.porteanimal",
                    ),
                ),
                (
                    "preco_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="servicos.preco"
                    ),
                ),
                (
                    "tipo_servico_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicos.tiposervico",
                    ),
                ),
                (
                    "usuario_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
