# Generated by Django 4.2.7 on 2023-12-07 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0002_animal_agendamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="data_agendamento",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 6, 22, 53, 10, 563033)
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="nome",
            field=models.CharField(default="Nome Padrão", max_length=50),
        ),
        migrations.AddField(
            model_name="animal",
            name="tipo",
            field=models.CharField(default="Tipo Padrão", max_length=50),
        ),
    ]
